### ISSUE TITLE
Many unresolved issues in RT

### ISSUE THREAD

**Issue by karenetheridge** [mfontani/Net-Amazon-Route53#11]
https://rt.cpan.org/Dist/Display.html?Queue=Net-Amazon-S3

**Comment by mfontani** [comment]
@karenetheridge what's Net::Amazon::S3's bug status related to this module? Granted, there are many bugs that still need fixing here…

**Comment by karenetheridge** [comment]
Terribly sorry, I got the wrong repository! moving to https://github.com/pfig/net-amazon-s3..
